# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

redirect_sylius_shop_product_index:
    path: /{_locale}/taxons/{slug}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: bitbag_sylius_elasticsearch_plugin_shop_list_products
        permanent: true
    requirements:
        slug: .+

bitbag_sylius_elasticsearch_plugin:
    resource: "@BitBagSyliusElasticsearchPlugin/Resources/config/routing.yml"


bitbag_sylius_cms_plugin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"

bitbag_sylius_wishlist_plugin:
    resource: "@BitBagSyliusWishlistPlugin/Resources/config/routing.yml"

bitbag_sylius_mollie_plugin:
    resource: "@BitBagSyliusMolliePlugin/Resources/config/routing.yml"

bitbag_sylius_mailchimp_plugin:
    resource: "@BitBagSyliusMailChimpPlugin/Resources/config/routing.yml"
    prefix: /

bitbag_shipping_export_plugin:
    resource: "@BitBagSyliusShippingExportPlugin/Resources/config/routing.yml"
    prefix: /admin

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

bitbag_sylius_invoicing_plugin:
    resource: "@BitBagSyliusInvoicingPlugin/Resources/config/routing.yml"
    prefix: /admin

bitbag_sylius_adyen_plugin:
    resource: "@BitBagSyliusAdyenPlugin/Resources/config/routing.yml"

bitbag_sylius_acl_plugin:
    resource: "@BitBagSyliusAclPlugin/Resources/config/routing.yml"

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

bitbag_admin_export_all_new_shipments:
    path: /shipping-exports/export/all
    methods: [POST, PUT]
    defaults:
        _controller: bitbag.controller.shipping_export:exportAllNewShipmentsAction
        _bitbag_sylius_acl_plugin:
            label: action.export_all_shipments
            parent: shipping_exports

bitbag_admin_export_single_shipment:
    path: /shipping-exports/export/{id}
    methods: [POST, PUT]
    defaults:
        _controller: bitbag.controller.shipping_export:exportSingleShipmentAction
        _bitbag_sylius_acl_plugin:
            label: action.export_single_shipments
            parent: shipping_exports

bitbag_admin_get_shipping_label:
    path: /shipping-exports/label/{id}
    defaults:
        _controller: bitbag.controller.shipping_export:getLabel
        _bitbag_sylius_acl_plugin:
            label: action.get_shipping_label
            parent: shipping_exports
