services:
    app.controller.inpost.redirect:
        class: AppBundle\Controller\Action\InPostRedirectAction
        arguments:
            - "@sylius.http_client"

    bitbag_sylius_quadpay_plugin.action.capture:
        class: AppBundle\Action\CaptureAction
        public: true
        tags:
            - { name: payum.action, factory: quadpay, alias: payum.action.capture }
